import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Feed from '../Components/Feed'
import { useContext } from 'react'
import { AuthContext } from '../context/auth'
import { useRouter } from 'next/router'
import InterOb from "../components/InterOb";

export default function Home() {
  const {user} = useContext(AuthContext);
  console.log(user?.uid);
  const Redirect = () =>{
    const router = useRouter();
    router.push("/login");
  }
  return (
    

    <div className={styles.container}>
      <Head>
        <title>JIFFYGram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../icon.png" />
      </Head>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome New Gramers
        </h1>
      <index />
        
      </main> */}

      {user?.uid?
        <Feed />:<Redirect />
      }
      
    </div>
  );
}
